In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [15]:
# define sequences
sequences = [
[1, 2, 3, 4],
[1, 2, 3],
[1]
]
# pad sequence
padded = pad_sequences(sequences,5,padding='post')
print(padded)

[[1 2 3 4 0]
 [1 2 3 0 0]
 [1 0 0 0 0]]


In [16]:
# define sequences
sequences = [6,5,67,2,1]
sequences = np.array(sequences)
sequences = sequences.reshape(len(sequences),1)
# pad sequence
padded = pad_sequences(sequences,5,padding='post')
print(padded)

[[ 6  0  0  0  0]
 [ 5  0  0  0  0]
 [67  0  0  0  0]
 [ 2  0  0  0  0]
 [ 1  0  0  0  0]]


In [19]:
# define sequences
sequences = [
    [1, 2, 3, 4],
[1, 2, 3],
[1]
]
# pad sequence
padded = pad_sequences(sequences,2,padding='post',truncating='post')
print(padded)

[[1 2]
 [1 2]
 [1 0]]
